export const MINUTES_LAST_POMODORO = 24
export const MINUTES_LAST_LONG_BREAK = 14
export const MINUTES_LAST_SHORT_BREAK = 4
export const SECONDS = 60
export const INTERVAL_IT_LAST_POMODORO_SECONDS = 1500
export const INTERVAL_IT_LAST_LONG_BREAK_SECONDS = 900
export const INTERVAL_IT_LAST_SHORT_BREAK_SECONDS = 300